spring.application.name=gestione_pagamento



#db
#server.port=8081 en pause pour tester gateway
spring.datasource.url = ${MYSQL_URL_PAGAMENTO}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}


#jpa
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=${SERVLET_CONTEXT_PATH}


#swagger
springdoc.api-docs.path=${API_DOCS_PATH}


# Connexion aRabbitMQ sulla porta esterna esposta
spring.rabbitmq.host=${RABBITMQ_HOST}
#spring.rabbitmq.port=${RABBITMQ_PORT}
#spring.rabbitmq.username=${RABBITMQ_USERNAME}
#spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# Configuration du Scheduler : 300000 ms = 5 minutes
cron.clean.payments.rate=${CRON_CLEAN_PAYMENTS_RATE}

#SMTP
auth.service.url=${AUTH_SERVICE_URL}

spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

